server:
  port: 8099
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: test
    password: test
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jy.model
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

